apiVersion: v1
kind: Secret
metadata:
  name: aux-service-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "PROD_ACCESSKEY456"
  AWS_SECRET_ACCESS_KEY: "PROD_SECRETKEY456"
  AUX_SERVICE_VERSION: "1.0.0"
