version: "3.9"

services:
  aux-service:
    build:
      context: ./aux-service
    container_name: aux-service
    ports:
      - "6000:6000"

  main-api:
    build:
      context: ./main-api
    container_name: main-api
    ports:
      - "5000:5000"
    environment:
      - AUX_SERVICE_URL=http://aux-service:6000
    depends_on:
      - aux-service
