apiVersion: v1
kind: Secret
metadata:
  name: main-api-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "PROD_ACCESSKEY123"
  AWS_SECRET_ACCESS_KEY: "PROD_SECRETKEY123"
  AUX_SERVICE_URL: "http://aux-service.default.svc.cluster.local:5000"
  MAIN_API_VERSION: "1.0.0"
